"""add cut_timing to fertilization

Revision ID: 5cba76e733fe
Revises: 4dee7b9bf13f
Create Date: 2023-01-18 22:39:50.627058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cba76e733fe"
down_revision = "4dee7b9bf13f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fertilization", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cut_timing",
                sa.Enum(
                    "first_cut",
                    "second_cut",
                    "third_cut",
                    "fourth_cut",
                    "non_mowable",
                    name="cuttiming",
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fertilization", schema=None) as batch_op:
        batch_op.drop_column("cut_timing")

    # ### end Alembic commands ###
