"""rename sub_suffix to partition

Revision ID: c07676c4b9f1
Revises: 0b803ff60a56
Create Date: 2024-06-23 20:37:44.150133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c07676c4b9f1"
down_revision = "0b803ff60a56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("field", schema=None) as batch_op:
        batch_op.add_column(sa.Column("partition", sa.Integer(), nullable=True))
        batch_op.drop_constraint("uq_field_base_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_field_base_id"), ["base_id", "partition", "year"]
        )
        batch_op.drop_column("sub_suffix")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("field", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_suffix", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f("uq_field_base_id"), type_="unique")
        batch_op.create_unique_constraint("uq_field_base_id", ["base_id", "sub_suffix", "year"])
        batch_op.drop_column("partition")

    # ### end Alembic commands ###
